services:
  web:
    build: .
    ports:
      - 8019:8080
    develop:
      watch:
        - action: sync
          path: ./static
          target: /app/static
        - action: rebuild
          path: ./main.go
