# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c59421c30bc847d05c2bc56254f2e278ed1a4ca2a0ee8921756e387164117e66710557a2ef54559efe08773b2402bd493b9640e5b92d1712f832b989377e0fc

test:
  secret_key_base: 1ccfa009c0f60d87967c18160868359daa25e55bbf06da91ccba8d8dcdaf52060bbc16a9bf40ae81cacf7e8554932f1533befc879ecd12d5025e2acad3173b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
